name: Compare functions
on: push
jobs:
  compare:
    runs-on: ubuntu-22.04
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          STARTWITH_FUNC: ${{ startWith('Hello', 'He') }}
          ENDWITH_FUNC: ${{ ENDWITH('Hello', 'lo') }}
