name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-22.04
    env:
      PASSWORD: "${{ secrets.PASSWORD }}"
      steps:
        - run: echo "${PASSWORD}"
        - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
